project:
  type: website
  output-dir: docs

website:
  title: "Parallel Rcpp"
  repo-url: https://github.com/astamm/parallel-rcpp/
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - text: "Slides"
        href: parallel-rcpp.qmd
      - text: "Lab"
        href: lab/hausdorff_dist.qmd
    right:
      - icon: github
        href: https://github.com/astamm/parallel-rcpp/

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
