project:
  type: website
  output-dir: docs

website:
  title: "Parallel Rcpp"
  repo-url: https://github.com/astamm/parallel-rcpp/
  repo-actions: [edit, source, issue]
  page-footer:
    background: light
    left: Copyright 2024, Aymeric Stamm
    right: This website is built with [Quarto](https://quarto.org/)
  navbar:
    left:
      - text: "Slides"
        href: parallel-rcpp.qmd
      - text: "Lab"
        menu:
          - text: "Lab"
            href: lab/hausdorff_dist.qmd
          - text: "Solution"
            href: lab/hausdorff_dist_solutions.qmd
    right:
      - icon: github
        href: https://github.com/astamm/parallel-rcpp/

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
