on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        run: |
           options(repos = "https://packagemanager.posit.co/cran/__linux__/jammy/latest")
           options(
             HTTPUserAgent = sprintf("R/%s R (%s)",
               getRversion(),
               paste(getRversion(), R.version$platform, R.version$arch, R.version$os)
             )
           )
           install.packages(c("rmarkdown", "bench", "BH", "futureverse", "gt", "Rcpp", "RcppParallel", "RcppProgress", "RcppThread", "roahd", "sitmo", "tidyverse"))
        shell: Rscript {0}

      - name: Setup OpenMP
        run: |
          brew install clang-omp
          mkdir ~/.R
          echo "CPPFLAGS += -Xclang -fopenmp\nLDFLAGS += -lomp" > ~/.R/Makevars
        shell: bash

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
